version: "3.9"
services:
  frontend:
    build: frontend
    ports:
      - "8080:80"
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: "DockerCompose"
      "DevelopDB:Login": sa
      "DevelopDB:Password": ${SA_PASSWORD}
    depends_on:
      - sql
    networks:
      - backend
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver/data:/var/opt/mssql/data
      - ./sqlserver/log:/var/opt/mssql/log
    networks:
      - backend
networks:
  backend: